# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools>=4.55", "brotli"]
# ///
"""Builds the app's Material Symbols icon fonts (D-016).

React Native cannot use variable-font axes or rely on ligatures on Android, so this script
cuts two static instances (outlined FILL=0 and filled FILL=1, weight 400, optical size 24)
from Google's variable font and subsets them to the icons listed in icons.txt. The app then
renders icons by codepoint (src/design/icons/glyphs.ts).

Usage: pnpm --filter @nujoom/tools-icons build   (after adding names to icons.txt)
"""

from __future__ import annotations

import io
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = Path(__file__).parent
REPO = HERE.parent.parent
CACHE = HERE / ".cache"
FONT_DIR = REPO / "apps" / "mobile" / "assets" / "fonts"
GLYPHS_TS = REPO / "apps" / "mobile" / "src" / "design" / "icons" / "glyphs.ts"

BASE = "https://github.com/google/material-design-icons/raw/master/variablefont/"
VARIABLE = "MaterialSymbolsOutlined%5BFILL,GRAD,opsz,wght%5D"


def fetch(name: str) -> bytes:
    CACHE.mkdir(exist_ok=True)
    cached = CACHE / name.replace("%5B", "[").replace("%5D", "]")
    if not cached.exists():
        with urllib.request.urlopen(BASE + name) as response:  # noqa: S310 (fixed https URL)
            cached.write_bytes(response.read())
    return cached.read_bytes()


def main() -> None:
    wanted = sorted({line.strip() for line in (HERE / "icons.txt").read_text().splitlines() if line.strip()})
    codepoints: dict[str, int] = {}
    for line in fetch(VARIABLE + ".codepoints").decode().splitlines():
        name, cp = line.split()
        codepoints[name] = int(cp, 16)
    missing = [n for n in wanted if n not in codepoints]
    if missing:
        raise SystemExit(f"Unknown icon names: {', '.join(missing)}")

    source = fetch(VARIABLE + ".ttf")
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for fill, family in ((0, "MaterialSymbolsOutlined"), (1, "MaterialSymbolsOutlinedFilled")):
        font = TTFont(io.BytesIO(source))
        static = instancer.instantiateVariableFont(font, {"FILL": fill, "GRAD": 0, "opsz": 24, "wght": 400})
        options = subset.Options()
        options.layout_features = []  # codepoints only; no ligatures needed
        options.notdef_outline = True
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=[codepoints[n] for n in wanted])
        subsetter.subset(static)
        out = FONT_DIR / f"{family}.ttf"
        static.save(out)
        print(f"{out.relative_to(REPO)}: {out.stat().st_size // 1024} KB")

    lines = [
        "// Generated by tools/icons/build.py from tools/icons/icons.txt. Do not edit.",
        "// Material Symbols Outlined codepoints (Apache License 2.0, Google).",
        "export const GLYPHS = {",
        *[f"  {n}: 0x{codepoints[n]:x}," for n in wanted],
        "} as const;",
        "",
        "export type IconName = keyof typeof GLYPHS;",
        "",
    ]
    GLYPHS_TS.parent.mkdir(parents=True, exist_ok=True)
    GLYPHS_TS.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{GLYPHS_TS.relative_to(REPO)}: {len(wanted)} icons")


if __name__ == "__main__":
    main()
